### PR TITLE
Introduce WebApplicationFirewallPolicy resource

### PR DESCRIPTION
**Pull request by houkms**
This PR introduces the input files for web_application_firewall_policy resource.

### CODE REVIEW

**Comment by houkms** [comment]
Above is the original version of the autorest.devops generated files.

**Comment by houkms** [comment]
The pipeline error is fixed in magic-modules [PR13](https://github.com/VSChina/magic-modules/pull/13)

**Comment by houkms** [comment]
@JunyiYi The generated terraform codes have been tested through basic/ complete/ update acctests, everything goes well.

**Comment by JunyiYi** [comment]
Thanks @houkms for the contribution, your resource has been merged into the official Terraform now!

**Pull request merged**
